In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.11.0'

Data preprocessing

In [3]:
dataset = pd.read_csv('/content/drive/MyDrive/Churn_Modelling.csv')
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [5]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [6]:
from sklearn.compose  import  ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder="passthrough")
x = np.array(ct.fit_transform(x))

In [7]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


splitting the dataset into the training set and test set

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size = 0.2, random_state=0)

feature scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

Part -2 Building the ANN

Initializing the ANN

In [10]:
ann = tf.keras.models.Sequential()

Adding the input layer and first hidden layer

In [11]:
# ann.add(tf.keras.Input(shape=(11,)))

In [12]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

Adding the second hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

adding the output layer

In [14]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

Part - 3 Training the ANN

compiling the ANN

In [15]:
ann.compile(optimizer='adam',loss = 'binary_crossentropy', metrics=['accuracy'])

Training theANN on the Training Set

In [ ]:
ann.fit(x_train,y_train,batch_size = 32 , epochs=20)

Epoch 1/20
250/250 [==============================] - 6s 8ms/step - loss: 0.5391 - accuracy: 0.7960
Epoch 2/20
250/250 [==============================] - 2s 6ms/step - loss: 0.4724 - accuracy: 0.7960
Epoch 3/20
250/250 [==============================] - 1s 5ms/step - loss: 0.4426 - accuracy: 0.8070
Epoch 4/20
250/250 [==============================] - 1s 5ms/step - loss: 0.4301 - accuracy: 0.8169
Epoch 5/20
250/250 [==============================] - 1s 5ms/step - loss: 0.4219 - accuracy: 0.8183
Epoch 6/20
250/250 [==============================] - 1s 5ms/step - loss: 0.4157 - accuracy: 0.8189
Epoch 7/20
250/250 [==============================] - 1s 4ms/step - loss: 0.4100 - accuracy: 0.8235
Epoch 8/20
250/250 [==============================] - 1s 5ms/step - loss: 0.4045 - accuracy: 0.8270
Epoch 9/20
250/250 [==============================] - 1s 4ms/step - loss: 0.3986 - accuracy: 0.8309
Epoch 10/20
250/250 [==============================] - 1s 4ms/step - loss: 0.3927 - accuracy: 0.8332

Part - 4 Making prediction and evaluation the model

Predicting the result of a single observation

Use our ANN model to predict if the customer with the following informations 

will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer ?

In [ ]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

In [ ]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)